## Python_Advanced_Assignment_22
1. What are the benefits of the built-in array package, if any?
2. What are some of the array package's limitations?
3. Describe the main differences between the array and numpy packages.
4. Explain the distinctions between the empty, ones, and zeros functions.
5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?
6. What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression A + n?
7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?
8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?
9. What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays?
10. What is the best way to use a Boolean array to mask another array?
11. What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute.
12. What is the dimensionality of a Boolean mask-generated array?

In [10]:
'''Ans 1:- 
Python's built-in array module provides an alternative to lists for handling
arrays of a specific data type. While lists can hold elements of different types,
arrays created using the array module are more memory-efficient and can only contain
elements of a single specified data type. This can be especially useful when dealing
with large datasets to save memory.

In summary, the array module's benefits include memory efficiency, better
performance for numerical computations, type control, and memory compactness, making it a
valuable option for tasks involving large homogeneous datasets where memory
optimization is crucial. Keep in mind that Python's ecosystem includes additional libraries
like NumPy that offer more advanced array manipulation capabilities.


Benefits:
1. Memory Efficiency: Arrays use less memory than lists since they store
elements of the same data type.
2. Performance: Arrays can offer better performance for numerical operations compared to lists.
3. Type Control: You can ensure that only elements of a specific type are stored in the array.
4. Compact: Arrays are more compact in memory, suitable for scenarios with limited memory resources.

Typecode must be:- b, B, u, h, H, i, I, l, L, q, Q, f or d
'''

from array import array

# Create an array of integers
int_array = array('d', [1.1, 2.9, 3.5, 4.8, 5.7])

# Calculate the sum of array elements
sum_elements = sum(int_array)
print(sum_elements)

18.0


In [14]:
'''Ans 2:- The array package in Python offers memory-efficient arrays with specific data
types, but it also has limitations to consider:-

1. Fixed Type: Arrays are restricted to a single data type, unlike lists that can
hold mixed types. This limits flexibility when dealing with heterogeneous data.

2. Limited Operations: Arrays lack the extensive methods of lists. While you
can't use common list methods directly, you can convert arrays to lists and vice
versa to perform those operations.

3. No Built-in Dynamic Resizing: Arrays have a fixed size upon creation. If you
need to resize an array, you have to create a new one and copy data, making dynamic
resizing less convenient.

In summary, the array package's limitations include the inability to hold
mixed data types, a reduced set of methods, and the lack of built-in dynamic
resizing. While it's suitable for specific memory-efficient tasks with homogeneous data,
its inflexibility and lack of versatility might not suit all use cases.

Limitations:
1. Homogeneous Type: Only elements of the same data type can be stored in an array.
2. Limited Methods: Array methods are more limited compared to lists.
3. Fixed Size: Array size is determined at creation and can't be dynamically changed.'''

from array import array

# Create an array of floats
float_array = array('f', [1.0, 2.5, 3.7])


# Example: Converting an array to a list
float_list = list(float_array)
print(float_list)

[1.0, 2.5, 3.700000047683716]


In [16]:
# Using the decimal module ensures accurate decimal representation

from decimal import Decimal

# Create an array of Decimals
decimal_array = array('d', [Decimal('1.0'), Decimal('2.5'), Decimal('3.7')])
print(decimal_array)

# Now the array contains precise decimal values

array('d', [1.0, 2.5, 3.7])


In [20]:
'''Ans 3:- Both the array module and the NumPy package are used to handle
arrays in Python, but they serve different purposes and offer varying
features:-

1. Functionality:-
array: Provides basic arrays with fixed data types,
suitable for simple tasks and memory optimization.

NumPy: Offers advanced multidimensional arrays with 
a wide range of mathematical and array operations for
scientific computing.

2. Data Types:-
array: Limited data types compared to NumPy.

NumPy: Supports a broader range of data types
and user-defined data types.

3. Operations:- 
array: Basic operations for iteration and simple calculations.

In summary, while the array module is suitable for basic
array storage with memory efficiency, NumPy excels in scientific
computing with its powerful array operations and multidimensional
array support. If your tasks involve complex mathematical
computations, NumPy is generally a more suitable choice.'''

# Using array
from array import array
int_array = array('i', [1, 2, 3, 4, 5])

# Using NumPy
import numpy as np
np_array = np.array([1, 2, 3, 4, 5])

# Element-wise multiplication
int_array *= 2  # Performs scalar multiplication
np_array *= 2   # Performs element-wise multiplication

print(f"int_array {int_array} and np_array {np_array}")

int_array array('i', [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]) and np_array [ 2  4  6  8 10]


In [21]:
'''
In this example, element-wise multiplication combines
corresponding elements from array1 and array2, while scalar-wise
multiplication multiplies each element of array1 by the scalar value 2.

'''
import numpy as np

# Element-wise multiplication
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([2, 3, 4, 5, 6])
result_element_wise = array1 * array2  # [1*2, 2*3, 3*4, 4*5, 5*6]

# Scalar-wise multiplication
scalar = 2
result_scalar_wise = array1 * scalar  # [1*2, 2*2, 3*2, 4*2, 5*2]

print(f"Element-wise result: {result_element_wise}")
print(f"Scalar-wise result: {result_scalar_wise}")

Element-wise result: [ 2  6 12 20 30]
Scalar-wise result: [ 2  4  6  8 10]


In [22]:
'''Ans 4:- The empty, ones, and zeros functions are part of the NumPy
package in Python and are used to create arrays with specific
characteristics. Here are the distinctions between these functions:

1. numpy.empty:-  
This function creates a new array without initializing its values.
The array elements will initially contain whatever values were 
already present in the allocated memory, which could be random
and not predictable.

It's useful when you need an array with a specific shape but 
don't require initial values, and you plan to fill it with data later.

2. numpy.ones:-

This function creates a new array filled with ones. You
can specify the shape of the array using a tuple.

It's commonly used when initializing arrays for
mathematical operations, as ones are neutral elements in many
operations (like multiplication).

3. numpy.zeros:-

This function creates a new array filled with zeros. Like
numpy.ones, you can specify the shape of the array using a tuple.

It's often used to initialize arrays before filling them
with actual data.

As empty creates an array without initializing values, 
which means the initial values are unpredictable and could vary
between runs or systems. If we need specific initial values, use
ones or zeros to ensure a well-defined starting point for our
array.'''

import numpy as np

# Creating arrays using the functions
empty_array = np.empty((3, 3))  # Create a 3x3 array with uninitialized values
ones_array = np.ones((2, 4))    # Create a 2x4 array filled with ones
zeros_array = np.zeros((5, 2))  # Create a 5x2 array filled with zeros

print("Empty Array:")
print(empty_array)

print("\nOnes Array:")
print(ones_array)

print("\nZeros Array:")
print(zeros_array)

Empty Array:
[[4.67296746e-307 1.69121096e-306 1.11260483e-306]
 [6.23053614e-307 2.22526399e-307 6.23053614e-307]
 [7.56592338e-307 9.34588061e-307 3.62651150e-317]]

Ones Array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Zeros Array:
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [23]:
'''Ans 5:- The fromfunction function in NumPy is used to construct
new arrays by applying a given function to each coordinate
along the specified shape. The role of the callable argument in
the fromfunction function is to provide a function that
calculates the values for the elements of the resulting array based
on their indices (coordinates) within the array.

In this example, the my_function callable takes two
arguments (x and y) which represent the indices of the array
elements along their respective dimensions. The fromfunction
function uses this callable to populate the array with values based
on the function's result for each combination of indices.

So, the callable argument's role is crucial in determining
how the values are computed for each element of the newly
created array based on its indices. It allows you to create arrays
with customized patterns or calculations.'''

import numpy as np

# Define a callable function
def my_function(x, y):
    return x + y

# Create a 3x3 array using the fromfunction function
result_array = np.fromfunction(my_function, (3, 3))
print(result_array)

[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]


In [25]:
'''Ans 6:- When a NumPy array is combined with a single-value operand
through addition (A + n), NumPy performs element-wise addition.
The scalar value n is added to each element in the array A,
creating a new array with the same shape as A.

Each element of the array A is added with the scalar n,
resulting in an array where each element is increased by 10. This
behavior of element-wise addition makes it convenient to apply
scalar operations to entire arrays without the need for explicit
loops.'''

import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])
n = 10

# Element-wise addition of scalar n to each element in array A
result = A + n  
print(result)

[[11 12 13]
 [14 15 16]]


In [29]:
'''Ans 7:- Yes, array-to-scalar operations can use combined
operation-assign operators like += or *=. When these operators are used,
the scalar value is combined with each element of the array,
and the result is assigned back to the original array. This
modifies the array in place.In the example, A += 20 adds 20 to each
element in array A, and B *= 20 multiplies each element in array B
by 20. The original arrays are modified in place to reflect
the results of the combined operation-assign operators.'''

import numpy as np

A = np.array([1, 2, 3, 4, 5])

# Using combined operation-assign operators
# Adds 10 to each element of the array A
A += 20  
print(A)

B = np.array([1, 2, 3, 4, 5])

# Using combined operation-assign operators
# Multiplies each element of the array B by 2
B *= 20   
print(B)

[21 22 23 24 25]
[ 20  40  60  80 100]


In [33]:
'''Ans 8:- In NumPy, arrays can contain fixed-length strings. When
creating a NumPy array with a specified data type, we can use the S
specifier followed by a number to indicate the maximum string
length.  If we attempt to allocate a longer string to an array
element than its specified fixed length, NumPy will truncate the
string to fit within the specified length. No error or warning
will be raised. 

In the example, the original string 'pineapple' is longer
than the fixed length of 6 characters specified for the
str_array. When assigned, the string is truncated to fit within the
specified length, resulting in 'pineap'. This behavior ensures that
the array elements conform to the defined data type and
length.'''

import numpy as np

# Creating a NumPy array with fixed-length strings limited to 6 characters
str_array = np.array(['apple', 'banana', 'cherry'], dtype='S6')  

# Attempt to allocate a longer string
# 'pineapple' is truncated to 'pineap'
str_array[0] = 'pineapple'  
print(str_array)

[b'pineap' b'banana' b'cherry']


In [34]:
'''Ans 9:- When we combine two NumPy arrays using addition (+) or
multiplication (*), the arrays are combined element-wise. This means that
corresponding elements from both arrays are operated on, resulting in a
new array with the same shape as the input arrays.

Conditions for Combining:-

1. The arrays must have compatible shapes, which usually
means the same dimensions or dimensions that can be broadcasted
(extended to match).

In this example, the arrays A and B are combined
element-wise using both addition and multiplication. The conditions for
combining are met since both arrays have the same shape. The result
arrays are [5, 7, 9] for addition and [4, 10, 18] for
multiplication, where each element is the result of the respective
operation applied to the corresponding elements from A and B.'''

import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Element-wise addition
result_addition = A + B

# Element-wise multiplication
result_multiplication = A * B  

print("Addition:", result_addition)
print("Multiplication:", result_multiplication)

Addition: [5 7 9]
Multiplication: [ 4 10 18]


In [39]:
'''Ans 10:- The best way to use a Boolean array to mask another array
in NumPy is to directly use the Boolean array as an index to
select the desired elements from the target array. This process
is often referred to as "array masking" or "Boolean
indexing."

In this example, the Boolean array mask is used to select
elements from the data array. The True values in the mask
correspond to the positions of elements to be selected. The resulting
masked_data array contains only the elements from data where the
corresponding positions in the mask are True.  This approach is
efficient and concise, enabling us to filter and manipulate arrays
based on specific conditions using Boolean arrays as masks.'''

import numpy as np

data = np.array([10, 20, 30, 40, 50])
mask = np.array([True, False, True, False, True])

masked_data = data[mask]
print(f"Masked {masked_data}")

Masked [10 30 50]


In [43]:
'''Ans 11:- Sorting algorithms based on execution speed can be
influenced by various factors, including data size and computer
hardware. However, here are three ways to calculate the standard
deviation using standard Python and its packages, ranked by general
execution speed:-

1. NumPy Package (Fastest): NumPy's built-in numpy.std()
function is highly optimized for fast array calculations.

2. Statistics Module (Moderate): The statistics module in the
Python standard library offers a stdev() function for calculating
the standard deviation

3. Pure Python (Slower): Calculating the standard deviation
from scratch using pure Python is slower for larger datasets

In terms of speed, NumPy is generally the fastest due to
its optimized C implementation. The statistics module provides
a moderate balance between speed and simplicity, while pure
Python code is slower for larger datasets due to its interpreted
nature.'''

# NumPy Package
import numpy as np
data = np.array([10, 20, 30, 40, 50])
std_numpy = np.std(data)


# Statistics Module
import statistics
data = [10, 20, 30, 40, 50]
std_stats = statistics.stdev(data)

# Pure Python 
data = [10, 20, 30, 40, 50]
mean = sum(data) / len(data)
squared_diffs = [(x - mean) ** 2 for x in data]
std_pure_python = (sum(squared_diffs) / len(data)) ** 0.5

print(f"NumPy Package:- {std_numpy} \nStatistics Module:- {std_stats} \nPure Python:- {std_pure_python}")

NumPy Package:- 14.142135623730951 
Statistics Module:- 15.811388300841896 
Pure Python:- 14.142135623730951


In [46]:
'''Ans 12:- A Boolean mask-generated array takes on a dimensionality
determined by the shape of the mask itself. When using a Boolean mask
to index an array, the resulting array retains the dimensions
of the mask. For instance, if you have a 2D array and apply a
Boolean mask to it, the resulting array will also be 2D, with
values filled where the mask is True and masked (usually False)
elsewhere.

The resulting array has a dimensionality of 1,
corresponding to the flattened version of the original array where the
mask is True. In general, the dimensionality of a Boolean
mask-generated array mirrors the shape of the mask, with True values
indicating which elements from the original array are selected.'''

import numpy as np
# 2D array A
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Boolean mask M
M = np.array([[True, False, True],
              [False, True, False],
              [True, False, True]])

result = A[M]
print(result)

[1 3 5 7 9]
